### PR TITLE
NTBS-2987 Add SQL CMD variable for number of reporting years

### PR DESCRIPTION
**Pull request by JoshCadney**
Allow us to set the number of reporting years of data in the publish profile, so that we can change it on a per-environment basis

### CODE REVIEW

**Review by aptemus — APPROVED** [review]
Looks good

**Review by LeoCie — APPROVED** [review]
Looks good, does the local publish profile need to be updated too now?

**Comment by aptemus** [comment]
> Looks good, does the local publish profile need to be updated too now?

Yes I think so - but that doesn't live in github does it?

**Comment by LeoCie** [comment]
> > Looks good, does the local publish profile need to be updated too now?
> 
> Yes I think so - but that doesn't live in github does it?

I think the template does, it's called DEV-reporting.publish.xml. Isn't a huge issue anyway!

**Pull request merged**
